matrix:
  include: 
    - os: linux
      dist: trusty
      compiler: g++
    - os: linux
      compiler: clang++
    - os: osx
      compiler: clang++  

language: cpp

script:
- java -Djava.library.path=. XPPQDemo
- java XPPQDemo