matrix:
  include: 
    - os: linux
      dist: trusty
      compiler: g++
    - os: linux
      compiler: clang++
    - os: osx
      compiler: clang++  
      env: JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Headers/

language: java

script:
- make -j 4
- java -Djava.library.path=. XPPQDemo