matrix:
  include: 
    - os: linux
      dist: trusty
      compiler: g++
    - os: linux
#      compiler: clang++
      env: CXX=clang++
    - os: osx
      compiler: clang++  

language: java

script:
- make -j 4
- java -Djava.library.path=. XPPQDemo